[tool.poetry]
name = "test-task-doctor-web"
version = "0.1.0"
description = ""
authors = ["BAIBASH1 <gazinyr2014@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
